pull_request_rules:
  - name: Automatic merge for Jacoco pull requests
    conditions:
      - base=main
      - author=github-actions[bot]
      - label=jacoco
    actions:
      merge:
        method: merge

  - name: Automatic delete branch after merge of Jacoco pull requests
    conditions:
      - base=main
      - author=github-actions[bot]
      - label=jacoco
      - merged
    actions:
      delete_head_branch: { }
