# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'target/site/jacoco/**'
    - '.github/badges/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'target/site/jacoco/**'
    - '.github/badges/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew gradlew test --tests com.dragonboat.game.*UnitTest
      
    - name: Run integration tests
      run: ./gradlew gradlew test --tests com.dragonboat.game.*IntegrationTest --fail-fast

    - name: Finally, run skipping tests
      run: ./gradlew build -x test
      
