# This workflow will create a code coverage label

name: Jacoco Coverage

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'target/site/jacoco/**'
    - '.github/badges/**'
    
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'target/site/jacoco/**'
    - '.github/badges/**'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Copy Jacoco CSV
      run: |
        cp core/build/jacoco/test/jacocoTestReport.csv target/site/jacoco/jacoco.csv

    - name: Generate Jacoco Badge
      id: jacoco
      uses: AlecCoates/jacoco-badge-generator@v1.3.0

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        
    - name: Create pull request
      if: ${{ github.event_name == 'push' }}
      uses: peter-evans/create-pull-request@v3.8.0
      with:
        title: "Autogenerated Jacoco Coverage Badge"
        body: >
          Autogenerated Jacoco coverage badge, generated by
          the [jacoco-badge-generator](https://github.com/AlecCoates/jacoco-badge-generator)
          GitHub action.
        commit-message: "Autogenerated Jacoco Coverage Badge"
        branch: create-pull-request/badge
        delete-branch: true
        labels: jacoco

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
